const SAVE_LOGIN_USER = 'SAVE_LOGIN_USER';
const SAVE_THEME = 'SAVE_THEME';
const SAVE_IS_THEME_DARK = 'SAVE_IS_THEME_DARK';

export default {
  SAVE_LOGIN_USER,
  SAVE_THEME,
  SAVE_IS_THEME_DARK
};
